import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from './store';
import { Movie } from '../types/movie';
import {HIDE_LOADER, SHOW_LOADER} from './types'

export interface MovieList {
  moviesList: Movie[];
  status: 'idle' | 'loading' | 'failed';
}

const initialState: MovieList = {
  moviesList: [],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchMoviesAsync = createAsyncThunk(
  'movies/fetchAllMovies',
  async () => {
    const response = await fetch('http://localhost:4000/movies?searchBy=title')
      const json = await response.json()
    // The value we return becomes the `fulfilled` action payload
    return json.data;
  }
);

export const moviesSlice = createSlice({
  name: 'movies',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    showLoader: ():any => {
      return {
        type: SHOW_LOADER,
      };
    },
    hideLoader: ():any => {
      return {
        type: HIDE_LOADER,
      };
    },
    fetchMovies: ():any => {

    }


    // increment: (state) => {
    // Redux Toolkit allows us to write "mutating" logic in reducers. It
    // doesn't actually mutate the state because it uses the Immer library,
    // which detects changes to a "draft state" and produces a brand new
    // immutable state based off those changes
    //   state.value += 1;
    // },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchMoviesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchMoviesAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.moviesList = action.payload;
      })
      .addCase(fetchMoviesAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

export const { showLoader, hideLoader } = moviesSlice.actions;

export const selectMovies = (state: RootState) => state.movies;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state: RootState) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default moviesSlice.reducer;
